# Generated by Django 4.0.6 on 2022-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
